name: Tests

on:
  - push
  - pull_request

jobs:
  ubuntu:
    name: Ubuntu 20.04
    runs-on: ubuntu-20.04
    steps:
      - name: GitHub repository checkout
        uses: actions/checkout@v3
      - name: Run script
        run: ./scripts/test.sh --build
